spring:
  application:
    name: AccountApi
  datasource:
    url: jdbc:mysql://localhost:3306/Account
    username: root
    password: sung2561
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 운영 환경에서는 validate 또는 제거 권장
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
    defer-datasource-initialization: true
    cloud:
      openfeign:
        autoconfiguration:
          jackson:
            enabled: true
server:
  port: 8081

logging:
  level:
    root: info
    org.hibernate.SQL: DEBUG # Hibernate 실행 쿼리 출력
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # 바인딩된 파라미터 확인
    org.springframework.transaction.interceptor: DEBUG # 트랜잭션 디버깅 로그
    org.springframework.cloud.openfeign: DEBUG # Feign 디버깅 로그
    org.springframework.web.client.RestTemplate: DEBUG # RestTemplate 로깅


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL # 전체 요청/응답 로깅
      userClient:
        loggerLevel: FULL # 특정 클라이언트 로깅 설정
    default-configuration: none # 기본 설정 무효화

